// Generated by CoffeeScript 1.8.0
define(function() {
  var init;
  init = function(options) {
    return console.log('working!');
  };
  return {
    aPAGE: function(options) {
      return init(options);
    }
  };
});
